name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  test:
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
          override: true
      - name: Clippy
        run: |
          cargo clippy --all-targets -- -D warnings
          cargo clippy --all-targets --features=tor -- -D warnings
          cargo clippy --all-targets --no-default-features -- -D warnings
          cargo clippy --all-targets --no-default-features --features=tor -- -D warnings
          cd test_utils
          cargo clippy -- -D warnings
          cargo clippy --features=tokio -- -D warnings
          cd ..
          cd integration-tests
          cargo clippy -- -D warnings
          cargo clippy --no-default-features -- -D warnings
          cd ..
      - name: Install 3proxy
        run: |
          cd $HOME
          curl -OL https://github.com/3proxy/3proxy/archive/refs/tags/0.8.13.tar.gz
          tar xvf 0.8.13.tar.gz
          cd 3proxy-0.8.13 && ln -s Makefile.Linux Makefile && make -j$(nproc)
          sudo apt-get update
          sudo apt-get install socat -y
      - name: Build
        run: |
          cargo build --examples
          cargo build --verbose --all
          cargo test --lib --verbose
      - name: Build Tor
        run: |
          cargo build --examples --features=tor
          cargo build --verbose --all --features=tor
          cargo test --lib --verbose --features=tor
      - name: Build No-Default Features
        run: |
          cargo build --examples --no-default-features
          cargo build --verbose --all --no-default-features
          cargo test --lib --verbose --no-default-features
      - name: Build No-Default Features Tor
        run: |
          cargo build --examples --no-default-features --features=tor
          cargo build --verbose --all --no-default-features --features=tor
          cargo test --lib --verbose --no-default-features --features=tor
      - name: Integration tests
        working-directory: ./integration-tests
        run: |
          env PATH=$HOME/3proxy-0.8.13/src:$PATH tests/integration_tests.sh
