name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  test:
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Install 3proxy
        run: |
          cd $HOME
          curl -OL https://github.com/3proxy/3proxy/archive/refs/tags/0.8.13.tar.gz
          tar xvf 0.8.13.tar.gz
          cd 3proxy-0.8.13 && ln -s Makefile.Linux Makefile && make -j$(nproc)
          sudo apt-get update
          sudo apt-get install socat -y
      - name: Run tests for tokio
        run: |
          cargo build --examples
          cargo build --verbose --all
          cargo test --lib --verbose
          env PATH=$HOME/3proxy-0.8.13/src:$PATH tests/integration_tests.sh
      - name: Run tests for futures
        run: |
          cargo test --lib --verbose
          env PATH=$HOME/3proxy-0.8.13/src:$PATH tests/integration_tests.sh
